Module03/cs260sandbox/hop/musicstore/payment/urls.py
from django.conf.urls import url
from . import views

app_name = "payment_ns"

urlpatterns = [
    url(r'^$', views.pay, name="pay"),
    url(r'^help/$', views.help, name="help"),
    url(r'^refund/$', views.refund, name="refund"),
    url(r'^(?P<payment_type>\D+)/',
        views.pay, {'discount': '40'}, name="pay_detals"),
]

Module03/cs260sandbox/hop/musicstore/urls.py
from django.urls import include
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',TemplateView.as_view(template_name='homepage.html')),
    url(r'^payment/', include('musicstore.payment.urls',namespace="payment_ns")),
]

Module03/cs260sandbox/hop/musicstore/payment/views.py
from django.shortcuts import render
from django.template.response import TemplateResponse

# Create your views here.

# Set default payment type to creditcard
def pay(request, payment_type="Creditcard",discount=0):
    # 'city' has value 'Seattle' or '' if city not in url
    # 'zipcode' has value '98101' or '' if zipcode not in url
    city = request.GET.get('city', 'N/A')
    zipcode = request.GET.get('zipcode', 'N/A')
    # Create an address dictionary
    address = {'city':city, 'zipcode':zipcode}
    return render(request,'payment/pay.html', {'address': address, 'payment_type' : payment_type, 'discount': discount})

def help(request):
	contact_name = 'Dustin'
	contact_address = {'sector': '#385','city':'Sabody','planet':'Moon'}
	contact_phone = ['123-456-789','987-654-321']
	contact_hours = ((0, 'Mon-Thu 7AM-12PM'),(1,'Fri 1PM-5PM'),(2,'Sat-Sun 7AM-10AM'))
	# Package up all variables into a dictionary
	contact_info = {'contact_name':contact_name,'contact_address':contact_address, 'contact_phone':contact_phone, 'contact_hours':contact_hours}
	return render(request,'payment/help.html', contact_info)

def refund(request):
	contact_name = 'Dustin'
	contact_address = {'sector': '#385','city':'Sabody','planet':'Moon'}
	contact_phone = ['123-456-789','987-654-321']
	contact_hours = ((0, 'Mon-Thu 7AM-12PM'),(1,'Fri 1PM-5PM'),(2,'Sat-Sun 7AM-10AM'))
	# Package up all variables into a dictionary
	contact_info = {'contact_name':contact_name,'contact_address':contact_address, 'contact_phone':contact_phone, 'contact_hours':contact_hours}
	return TemplateResponse(request,'payment/refund.html', contact_info)

Module03/cs260sandbox/hop/musicstore/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Music Store</title>

    <!-- Custom fonts for this theme -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet"
        type="text/css">

    <!-- Theme CSS -->
    <link href="{% static 'css/freelancer.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="/">Music Store</a>
            <button
                class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded"
                type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive"
                aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'payment_ns:pay' %}">Payment</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'payment_ns:help' %}">Payment
                            Assistance</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Masthead -->
    <header class="masthead bg-primary text-white text-center">
        <div class="container d-flex align-items-center flex-column">

            <!-- Masthead Heading -->
            <h1 class="masthead-heading text-uppercase mb-0">Music Store</h1>

            <!-- Icon Divider -->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon">
                    <i class="fas fa-star"></i>
                </div>
                <div class="divider-custom-line"></div>
            </div>

            <!-- Masthead Subheading -->
            <p class="masthead-subheading font-weight-light mb-0">CS 555 - Django Web Development</p>

        </div>
    </header>

    <!-- Main Section -->
    <section class="page-section portfolio" id="portfolio">
        <!-- Main Block -->
        {% block main %}{% endblock %}
    </section>

    <!-- Copyright Section -->
    <section class="copyright py-4 text-center text-white">
        <div class="container">
            <small>Copyright &copy; CityU 2019</small>
        </div>
    </section>

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-to-top d-lg-none position-fixed ">
        <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Contact Form JavaScript -->
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/contact_me.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/freelancer.min.js' %}"></script>

</body>

</html>

Module03/cs260sandbox/hop/musicstore/templates/homepage.html
{% extends "base.html" %}
{% block main%}

<!-- Main Section Heading -->
<h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Homepage</h2>

<!-- Icon Divider -->
<div class="divider-custom">
    <div class="divider-custom-line"></div>
    <div class="divider-custom-icon">
        <i class="fas fa-star"></i>
    </div>
    <div class="divider-custom-line"></div>
</div>

<!-- Main Content -->
<div style="text-align: center;">
    <a class="btn btn-primary" href="{% url 'payment_ns:pay' %}" role="button" style="margin: 50px;font-size: 30px;font-weight: bold;">View Payment</a>
    <a class="btn btn-primary" href="{% url 'payment_ns:help' %}" role="button" style="margin: 50px;font-size: 30px;font-weight: bold;">Payment Assistance</a>
</div>

{% endblock%}